apiVersion: apps/v1
kind: Deployment
metadata:
  name: chmodcalcapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chmodcalcapp
  template:
    metadata:
      labels:
        app: chmodcalcapp
    spec:
      containers:
        - name: chmodcalcapp
          image: dielawnk8s/chmodcalcapp:v4.0
          ports:
            - containerPort: 8501
